#if defined _tools_fwd_included
  #endinput
#endif
#define _tools_fwd_included

#include <tools/tools_version>

//Don't work yet
/*
forward eng_message_begin(msg_dest,msg_type,Float:pOrigin[3],ed);
forward eng_message_end();
forward eng_write_byte(iValue);
forward eng_write_char(iValue);
forward eng_write_short(iValue);
forward eng_write_long(iValue);
forward eng_write_angle(Float:flValue);
forward eng_write_coord(Float:flValue);
forward eng_write_string(sz[]);
forward eng_write_entity(iValue);
*/